### ISSUE TITLE
broken link in Getting Started/Installation.html

### ISSUE THREAD

**Issue by twalenzyk** [openhab-scripters/openhab-helper-libraries#169]
I've just installed the scripts on my Raspberry pi. The documentation on "Getting started/Installatrion.html" is quite comprehensive, but under Point 10 there is a Quickstart guide mentioned, which I cannot find. 

I assume the guide has been moved, but the link in the doc has been forgotten to correct.

**Comment by openhab-5iver** [comment]
Thank you for reporting this! I've read through the docs so many times... not sure how I could have possibly missed this.  I take it you mean Jython step 11. Just ignore that step (it shouldn't be there any more). I'm also seeing some oddities with the numbering, but it corrects after switching between languages. I'll get this fixed up!

**Comment by twalenzyk** [comment]
> ... you mean Jython step 11...

You're assumption is correct. I meant 11 not 10. Thanks a lot.

**Comment by openhab-5iver** [comment]
Fixed in #174.
