### ISSUE TITLE
Rules documentation examples use "tag" while it should be "tags"

### ISSUE THREAD

**Issue by shutterfreak** [openhab-scripters/openhab-helper-libraries#178]
**Describe the bug**
**Documentation bug** in [Guides / Rules](https://openhab-scripters.github.io/openhab-helper-libraries/Guides/Rules.html)

The documentation is inconsistently using `tag` and  `tags` to refer to the `tags` keyword argument in the `@rule()` decorator.

**Expected behavior**
Update the documentation and the examples to use `tags=[]` instead of `tag=[]`.

**Comment by openhab-5iver** [comment]
Fixed... it'll show up next time I push the pages.
