### ISSUE TITLE
[Jython Docs] Read/Add/Remove Item metadata needs updating

### ISSUE THREAD

**Issue by rkoshak** [openhab-scripters/openhab-helper-libraries#184]
The documentation for manipulating Item Metadata leads one down the rabbit hole or link to link to PR to PR. The main link is to a forum thread which links to a PR submitted by MJ Cummings with a class to manipulate metadata. But the class doesn't exist in the community folder under lib where it looks like it is supposed to be. Searching and clicking around shows that the the class has been superseded by metadata.py in the core. 

As I learn how all this stuff works I don;t mind taking a hand at writing something up. But this issue is to make sure this gap doesn't get forgotten.

**Comment by CrazyIvan359** [comment]
You are correct, looks like that section of "But How Do I?" didn't get updated when we transferred it to Sphinx. Feel free to make a PR with some examples, or put the content here and either Scott or I can add it to the docs.

For the time being, the page for the core module [`metadata.py`](https://openhab-scripters.github.io/openhab-helper-libraries/Python/Core/Packages%20and%20Modules/metadata.html) has documentation on each of the functions which hopefully will be enough to get moving with metadata. Let me know if you have any questions or issues with it.
