### ISSUE TITLE
Jython `core.utils` page is missing in docs

### ISSUE THREAD

**Issue by CrazyIvan359** [openhab-scripters/openhab-helper-libraries#187]
The [`core.utils`](https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Core/automation/lib/python/core/utils.py) module does not have a page in the docs.

**Comment by openhab-5iver** [comment]
As I mentioned to Rich in the forum, this is fixed... I just need to commit.

**Comment by CrazyIvan359** [comment]
Oops, I must have missed/forgotten that this was discussed.

I will kill my PR. Should I close this issue or will you do it with the commit?

**Comment by openhab-5iver** [comment]
I will close it in the PR. I haven't looked at what you put in your PR though... if you've added anything other than autodoc then I'll copy it over.

**Comment by CrazyIvan359** [comment]
PR deleted, but no, nothing more than autodoc

**Comment by openhab-5iver** [comment]
Closed in #209
