### ISSUE TITLE
[idealarm] No module named openhab in <script> at line number 2

### ISSUE THREAD

**Issue by duiffie** [openhab-scripters/openhab-helper-libraries#200]
After a clean installation of openHAB 2.4 and import of the helper-libraries and idealarm scripts, the following error appears in openhab.log:
```
2019-08-01 21:51:30.311 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/community/idealarm/idealarm.py'
2019-08-01 21:51:36.310 [ERROR] [ipt.internal.ScriptEngineManagerImpl] - Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/python/community/idealarm/idealarm.py': ImportError: No module named openhab in <script> at line number 2
```

1. Clean installation of openHAB 2.4
2. Clean installation of the openhab-helper-libraries
3. Clean installation of the idealarm libraries
4. See error in log after starting openHAB

I expect a proper start of idealarm instead of the above error.

**Environment (please complete the following information):**
 - Jython version: 2.7.0 standalone
 - openHAB version: 2.4.0
 - Release: today's code

**Comment by openhab-5iver** [comment]
I know this error, but I can't remember the cause. Do you not have any Items defined yet?

**Comment by duiffie** [comment]
only the basics needed for idealarm:

```
Group G_PersistOnChange // Persist on change and system start up
Group G_PersistOnUpdate // Persist on change and system start up. For temp, humidity sensors etc.

Group G_VirtualDevice      (G_PersistOnChange)
Group G_Timer
Group G_Alarm              (G_PersistOnChange)
Group G_Alarm_Z1           (G_Alarm)
Group G_Alarm_Z2           (G_Alarm)
Group G_AlarmArmingMode    (G_Alarm)
Group G_AlarmStatus        (G_Alarm)

Number Z1_Arming_Mode          "Z1 Arming Mode: [MAP(en_armingmode.map):%s]"    <alarm>     (G_AlarmArmingMode)
Number Z1_Status               "Z1 Status: [MAP(en_zonestatus.map):%s]"         <alarm>     (G_AlarmStatus)

Switch Toggle_Z1_Armed_Away    "Toggle Z1 Armed Away"                           <switch>    (G_VirtualDevice)    {expire="1s,command=OFF"}
Switch Toggle_Z1_Armed_Home    "Toggle Z1 Armed Home"                           <switch>    (G_VirtualDevice)    {expire="1s,command=OFF"}

Number Z1_Open_Sections        "Z1 open sections [%.0f]"                        <door>      (G_VirtualDevice)

Switch Z1_Entry_Timer          "Z1 entry timer [%s]"                            <time>      (G_Timer)            {expire="15s,command=OFF"}
Switch Z1_Exit_Timer           "Z1 exit timer [%s]"                             <time>      (G_Timer)            {expire="2m,command=OFF"}
Switch Z1_Nag_Timer            "Z1 nag timer [%s]"                              <time>      (G_Timer)            {expire="4m,command=OFF"}
Switch Z1_Alert_Max_Timer      "Z1 alert maximum time [%s]"                     <time>      (G_Timer)            {expire="20s,command=OFF"}
```

**Comment by openhab-5iver** [comment]
It's coming back... the issue may be in your EXTRA_JAVA_OPTS. Does the hello_world script work for you?

**Comment by duiffie** [comment]
hello_world loads, but stays silent afterwards... I followed the installation instructions. My /etc/default/openhab2 contains:

`EXTRA_JAVA_OPTS="-Xbootclasspath/a:/etc/openhab2/automation/jython/jython-standalone-2.7.0.jar -Dpython.home=/etc/openhab2/automation/jython -Dpython.path=/etc/openhab2/automation/lib/python"`

**Comment by duiffie** [comment]
My automation directory tree without groovy and javascript, without idealarm and with hello_world.py:

`automation/
├── jsr223
│   └── python
│       ├── community
│       │   └── README.md
│       ├── core
│       │   ├── 000_startup_delay.py
│       │   └── components
│       │       ├── 100_DirectoryTrigger.py
│       │       ├── 100_OsgiEventTrigger.py
│       │       ├── 100_StartupTrigger.py
│       │       ├── 200_JythonBindingInfoProvider.py
│       │       ├── 200_JythonExtensionProvider.py
│       │       ├── 200_JythonItemChannelLinkProvider.py
│       │       ├── 200_JythonItemProvider.py
│       │       ├── 200_JythonThingProvider.py
│       │       ├── 200_JythonThingTypeProvider.py
│       │       └── 200_JythonTransform.py
│       └── personal
│           ├── hello_world.py
│           └── README.md
├── jython
│   └── jython-standalone-2.7.0.jar
└── lib
    └── python
        ├── community
        │   ├── __init__.py
        │   └── __init__$py.class
        ├── configuration.py
        ├── configuration$py.class
        ├── core
        │   ├── actions.py
        │   ├── actions$py.class
        │   ├── date.py
        │   ├── date$py.class
        │   ├── __init__.py
        │   ├── __init__$py.class
        │   ├── items.py
        │   ├── jsr223.py
        │   ├── jsr223$py.class
        │   ├── links.py
        │   ├── log.py
        │   ├── log$py.class
        │   ├── metadata.py
        │   ├── osgi
        │   │   ├── events.py
        │   │   ├── events$py.class
        │   │   ├── __init__.py
        │   │   └── __init__$py.class
        │   ├── rules.py
        │   ├── rules$py.class
        │   ├── testing.py
        │   ├── triggers.py
        │   ├── triggers$py.class
        │   ├── utils.py
        │   └── utils$py.class
        └── personal
            └── __init__.py`

**Comment by openhab-5iver** [comment]
> hello_world loads
 Do you mean you see a debug log entry that the script loaded?
```
2019-08-01 16:50:27.788 [INFO ] [org.openhab.core.automation.module.script.rulesupport.internal.loader.ScriptFileWatcher] - Loading script 'python/personal/test/testScript1.py'
```
But no other logs for when the script executes? Hmmm... what do you see with `log:get` in the Karaf console? Your directory strucure looks OK, and there are $py.class files, so Jython should be in your classpath and it can find the libraries.

**Comment by duiffie** [comment]
Exactly, hello_world loaded:
`2019-08-01 22:41:49.231 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/core/components/200_JythonExtensionProvider.py'
2019-08-01 22:41:49.653 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/core/components/200_JythonItemChannelLinkProvider.py'
2019-08-01 22:41:49.759 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/core/components/200_JythonItemProvider.py'
2019-08-01 22:41:49.821 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/core/components/200_JythonThingProvider.py'
2019-08-01 22:41:49.870 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/core/components/200_JythonThingTypeProvider.py'
2019-08-01 22:41:49.921 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/core/components/200_JythonTransform.py'
2019-08-01 22:41:50.024 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/personal/hello_world.py'`

log:get:
`openhab> log:get                                                                                                                                                                                                                              
Logger                                             │ Level
───────────────────────────────────────────────────┼──────
ROOT                                               │ WARN
javax.jmdns                                        │ ERROR
org.apache.karaf.jaas.modules.audit                │ INFO
org.apache.karaf.kar.internal.KarServiceImpl       │ ERROR
org.apache.karaf.shell.support                     │ OFF
org.eclipse.jetty.util.thread.ThreadPoolBudget     │ ERROR
org.eclipse.smarthome                              │ INFO
org.eclipse.smarthome.automation                   │ INFO
org.jupnp                                          │ ERROR
org.openhab                                        │ INFO
org.ops4j.pax.url.mvn.internal.AetherBasedResolver │ ERROR
org.ops4j.pax.web.pax-web-runtime                  │ OFF
smarthome.event                                    │ INFO
smarthome.event.InboxUpdatedEvent                  │ ERROR
smarthome.event.ItemAddedEvent                     │ ERROR
smarthome.event.ItemRemovedEvent                   │ ERROR
smarthome.event.ItemStateEvent                     │ ERROR
smarthome.event.ThingAddedEvent                    │ ERROR
smarthome.event.ThingRemovedEvent                  │ ERROR
smarthome.event.ThingStatusInfoEvent               │ ERROR
`

> I'd like to troubleshoot hello_world before getting into ideAlarm.

Yes, I guess they share the same problem

**Comment by openhab-5iver** [comment]
Try triple ticks for the code fences ```

**Comment by openhab-5iver** [comment]
Looks like you missed steps 2 and 3

**Comment by duiffie** [comment]
That seems to fix hello_world.py!

```2019-08-01 23:08:42.234 [INFO ] [rt.internal.loader.ScriptFileWatcher] - Loading script 'python/personal/hello_world.py'
2019-08-01 23:08:44.247 [DEBUG] [jsr223.jython.core.triggers         ] - when: target=[Time cron 0/10 * * * * ?], target_type=Time, trigger_target=cron, trigger_type=0/10 * * * * ?, old_state=None, new_state=None
2019-08-01 23:08:44.740 [DEBUG] [jsr223.jython.core.triggers         ] - when: Created cron_trigger: [Time_cron_0_10_]
2019-08-01 23:08:44.743 [DEBUG] [jsr223.jython.core.rules            ] - Added rule [Jython Hello World (cron decorators)]
2019-08-01 23:08:50.037 [INFO ] [Jython Hello World (cron decorators)] - Hello World!```

**Comment by openhab-5iver** [comment]
Cool... so things are working. Have you read through all of this? https://openhab-scripters.github.io/openhab-helper-libraries/Python/Community/ideAlarm.html

**Comment by duiffie** [comment]
Hmm, it does work now. Seems that I didn't do a really god job at rtfm... After adding the expire binding and setting up persistence it starts rolling now. Thanks!

**Comment by openhab-5iver** [comment]
Excellent... you are welcome!
