### ISSUE TITLE
[autoremote] Needs some docs

### ISSUE THREAD

**Issue by openhab-5iver** [openhab-scripters/openhab-helper-libraries#231]
@besynnerlig, could you please add in at least a description to the documentation for Autoremote? Or just give me some detail here and I'll add it in. I looked through the lucid repo but did not find anything.

https://openhab-scripters.github.io/openhab-helper-libraries/Python/Community/AutoRemote.html

https://github.com/openhab-scripters/openhab-helper-libraries/tree/master/Community/AutoRemote

**Comment by besynnerlig** [comment]
I'm abroad but I'll eventually have a look at this when I return. ;)

**Comment by openhab-5iver** [comment]
Closed in #256.
