### ISSUE TITLE
Having accented character in rule name leads to a UnicodeEncodeError

### ISSUE THREAD

**Issue by jenche** [openhab-scripters/openhab-helper-libraries#302]
I tried to define a rule with the following decorator:
`@rule(u'Contrôle de l\'alarme', description=u'Active ou désactive l\'alarme')`

When the script containing this rule loads, I get the following error:
`Error during evaluation of script 'file:/etc/openhab2/automation/jsr223/python/personal/alarme.py': UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 5: ordinal not in range(128) in <script> at line number 10`

Replacing the "ô" character in the rule name by "o" fixes the problem.
Surprisingly, having this character in the rule description doesn't cause any problem.

**Environment (please complete the following information):**
 - Jython version: 2.7.1 standalone
 - openHAB version: 2.5.1

**Comment by openhab-5iver** [comment]
Sometime soon I will need to do some unicode testing and cleanup. I'll take a look at this one tonight. My WAG is that there is a log entry causing the issue.

**Comment by openhab-5iver** [comment]
@jenche, it was a log entry as I suspected. I will submit a PR for this, but you can correct this by changing [line 129 of core.rules](https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Core/automation/lib/python/core/rules.py#L129) to...

```
log.debug(u"Added rule [{}]".format(rule.name))
```
In case you missed it, there's a 'u' added to make a unicode string :slightly_smiling_face:. You'll need to reload the module in your script (or restart OH) for the change to be picked up. Thank you for reporting this!

**Comment by jenche** [comment]
Great, thanks for fixing it that fast !

**Comment by jenche** [comment]
Mmmm, I applied the fix in core.rules as you told me, restarted openhab, but still have the same error.
Is it possible there's another unicode encoding problem elsewhere in the code ?

**Comment by openhab-5iver** [comment]
Yes, it is very possible! But in testing, I was able to use unicode in a rule name without error using this fix. What was your error?

**Comment by jenche** [comment]
It's exactly the same than in my first post :`UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 5: ordinal not in range(128) in <script> at line number 10`

**Comment by jenche** [comment]
Ah, found it.
Need to change line 98 in core/rules.py to `callback.log = logging.getLogger(u"{}.{}".format(LOG_PREFIX, name))`

**Comment by openhab-5iver** [comment]
My bad... I already have this, so I neglected to point out this change.... sorry about that!

**Comment by 5iver** [comment]
I finally got this merged in #372.
