### ISSUE TITLE
Class Decoration - CronTrigger - inputs map is empty

### ISSUE THREAD

**Issue by lukicsl** [openhab-scripters/openhab-helper-libraries#304]
I have realized that different from other triggers the CronTrigger is not filling the inputs map (parameter of the execute method).
This does not seem to be consistent compared to other trigger types, at least “module” should be populated with the trigger name.

More info here: [Class Decoration - CronTrigger - inputs map is empty](https://community.openhab.org/t/class-decoration-crontrigger-inputs-is-empty/94347)

**Comment by openhab-5iver** [comment]
This would need to be addressed in the [GenericCronTriggerHandler](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java) within openhab-core.

**Comment by lukicsl** [comment]
> This would need to be addressed in the [GenericCronTriggerHandler](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.automation/src/main/java/org/openhab/core/automation/internal/module/handler/GenericCronTriggerHandler.java) within openhab-core.

@openhab-5iver 
Opened an issue, there. Could you please help to make it more precise if it is missing something.
[GenericCronTriggerHandler does not give back context information](https://github.com/openhab/openhab-core/issues/1391)
