### ISSUE TITLE
[Area Triggers and Actions] name light_action hard coded in area_triggers.py

### ISSUE THREAD

**Issue by besynnerlig** [openhab-scripters/openhab-helper-libraries#307]
**Descrption of the bug**
The function name `light_action` function has been hard coded in the [area_trigger.py](https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Community/Area%20Triggers%20and%20Actions/automation/jsr223/python/community/area_triggers_and_actions/area_triggers.py) as

```
                        if not action_function_names or "light_action" in action_function_names:
                            start_action(item, True if event is not None else trigger_group.state in [ON, OPEN], "light_action")
```

The following modified code works better for me:
```
                        if not action_function_names or area_triggers_and_actions_dict["default_action_function"] in action_function_names:
                            start_action(item, True if event is not None else trigger_group.state in [ON, OPEN], area_triggers_and_actions_dict["default_action_function"])
```

The issue was originally discussed as [here](https://community.openhab.org/t/area-triggers-area-actions/81896/11?u=rroe).

**Comment by 5iver** [comment]
Resolved in #375
