### ISSUE TITLE
[Area Triggers and Actions] Add a way to trigger a replay of all the actions

### ISSUE THREAD

**Issue by besynnerlig** [openhab-scripters/openhab-helper-libraries#309]
When defining a custom `lights_action` I have the ability to dynamically change for example the brigthness setting for a device. The reason for doing that might vary but one scenario is that I'd like a light to follow the current mode normally but under certain conditions I'd like to alter the dim level. For example I'd like to have a certain basic illumination in a room but when someone passes (detected by a MD) I'd like to raise the dim level temporary and go back to the default values for the mode afterwards. There is no problem to code such a thing using a custom `lights_action` and some additional meta data except for that we'd need a way to trigger the "Mode or lux change" rule defined in `community/area_triggers_and_actions/area_triggers.py` . The topic has previously been discussed [here](https://community.openhab.org/t/area-triggers-area-actions/81896/12?u=rroe).

**Comment by 5iver** [comment]
I have yet to push the documentation, but please let me know if #361 implemented what you were looking for.
