### ISSUE TITLE
core.metadata get_metadata duplicate lines of code

### ISSUE THREAD

**Issue by jimtng** [openhab-scripters/openhab-helper-libraries#319]
In https://github.com/openhab-scripters/openhab-helper-libraries/blob/master/Core/automation/lib/python/core/metadata.py the function get_metadata line 71-72,

```
    metadata = metadata_registry.get(MetadataKey(namespace, item_name))
    return metadata_registry.get(MetadataKey(namespace, item_name))
```
Why the duplication?

**Comment by openhab-5iver** [comment]
Thank you for pointing this out. Take a look here...

https://github.com/openhab-scripters/openhab-helper-libraries/commit/dca5e5d22b1ee4ecbabb53b3293230960ca0a190#r39583902

I'd removed som unnecessary commented out code in the last commit to core.metadata.py and this line should have been removed too. This wouldn't break anything, but there no need to call the MetadataRegistry twice. I'll get it cleaned up.

**Comment by openhab-5iver** [comment]
I squeaked this into #327.
