### ISSUE TITLE
[Area Triggers and Actions] Refactor light_action

### ISSUE THREAD

**Issue by theiding** [openhab-scripters/openhab-helper-libraries#324]
The existing light_action code duplicates code for brightness > 0 and brightness == 0 handling and across the dimmer, switch and color handling. Collapsing the code will make it more readable and extensible, which will be helpful for users as light_action is meant to be customized by users.

**Comment by theiding** [comment]
I have the code available and am happy to submit the PR.

**Comment by 5iver** [comment]
Resolved in #361.
