### ISSUE TITLE
[Area Triggers and Actions] light_action throws exceptions

### ISSUE THREAD

**Issue by theiding** [openhab-scripters/openhab-helper-libraries#325]
light_action throws exceptions in two cases:
1) When a lux item is configured, but the lux item returns NULL an AttributeError is thrown
2) When no "low_lux_trigger" is configured on the item or area_triggers_and_actions_dict level then a KeyError is thrown

Desired behavior:
For 1) When a lux item returns NULL, no AttributeError should be logged and the reading should be treated as if it reported a lux level below the lux threshold. A warning should be logged that the lux item reported NULL.
For 2) When no "low_lux_trigger" is configured no KeyError should be logged and low_lux_trigger should default to infinity (i.e. all lux readings would be considered to be below the threshold). If lux_item_name is configured a warning should be logged that a lux item is configured without a low_lux_trigger.

 - Jython version: 2.7.0 standalone
 - openHAB version: 2.5.6-SNAPSHOT

**Comment by theiding** [comment]
Fix is of course trivial and I have the code available. Happy to submit the PR.

**Comment by 5iver** [comment]
1 and 2 are both resolved in #361.
