### ISSUE TITLE
[Area Triggers and Actions] Configurable brightness method for light_action

### ISSUE THREAD

**Issue by theiding** [openhab-scripters/openhab-helper-libraries#326]
The current implementation of light_action determines the brightness to be set as a function of lux level and mode. In more complex use cases other external factors need to be taken into account to determine brightness:
Example 1: Emphasize/boost a light if a neighboring light is on as described [here](https://community.openhab.org/t/area-triggers-area-actions/81896/12?u=theiding)
Example 2: Let an override item override the default brightness if it is set as described [here](https://community.openhab.org/t/proposal-activitymanager-for-consistent-handling-of-motion-triggers-and-their-timers/93448/16?u=theiding)

The ask is to support optional configuration of a brightness function that takes brightness, hue, saturation, item, active as input and returns a new brightness value. The passed in brightness/hue/saturation are the currently computed values; item and active are the values that light_action was invoked with. This then allows a concise implementation of additional brightness logic. If the method is configured it will be invoked and its return brightness will be applied to the item. 
This proposal allows clean customization without having to duplicate the entire light_action method while introducing minimal complexity. 

@openhab-5iver had responded to the original proposal of specific support for example 2 [that the functionality is too narrow to warrant the additional complexity](https://community.openhab.org/t/proposal-activitymanager-for-consistent-handling-of-motion-triggers-and-their-timers/93448/17?u=theiding). This proposal is significantly more generic and addresses a wide range of use cases, but the same concern of unneeded complexity may of course still be raised, in which case the same workaround would apply of customizing the entire light_action method.

**Comment by 5iver** [comment]
I do not feel the need to add more complexity to the light_action function. If you implement a custom action, please submit it as an example. If it is useful, I'll consider adding it into light_action.
