### ISSUE TITLE
The WeatherStationUploader community script is obsolete and should be removed

### ISSUE THREAD

**Issue by besynnerlig** [openhab-scripters/openhab-helper-libraries#347]
The [WeatherStationUploader](https://github.com/openhab-scripters/openhab-helper-libraries/tree/master/Community/WeatherStationUploader) is obsolete due to [end of service for the Weather Underground API](https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api). Therefore I suggest we retire (remove) the community script for WeatherStationUploader.

**Comment by openhab-5iver** [comment]
I would expect that the [API for The Weather Channel](https://weather.com/swagger-docs/call-for-code) also supports this functionality. Maybe we should just update the diocs to state that this no longer works and would need to be modified to use the new API? Maybe someone could look up the API docs to see what would need to change. It may be just the URL.

**Comment by besynnerlig** [comment]
> I would expect that the API for The Weather Channel also supports this functionality. Maybe we should just update the diocs to state that this no longer works and would need to be modified to use the new API? Maybe someone could [look into the API docs](https://weather.com/swagger-docs/call-for-code) to see what would need to change. It may be just the URL.

I haven't used the WeatherStationUploader for quite some time and I haven't had a look at The Weather Channel. My outdoor weather sensors don't seem to endure for very long in this climate so I gave up on the idea of having a personal weather station. We could do what you suggest however I won't be able to try it out at the moment. The script is also using the `getItemValue` and `getLastUpdate` functions (deprecated) from `core.utils` so it would need some "TLC" to be kept alive.
