### ISSUE TITLE
openhab-helper-libraries/Getting Started/Installation suggestions

### ISSUE THREAD

**Issue by RubyBailey** [openhab-scripters/openhab-helper-libraries#358]
I run OH on a RPI 3
Some suggestions to help update the documentation for others, like myself, that are struggling with basics:
7. Download the contents of this repository.  - It would be helpful to show the detailed steps required to complete this step. Download, using openhab account, copy, etc. 
I struggled with this a very long time and came up with a method where:
1.	download using windows through the samba directories
2.	copied automation into sounds directory
3.	created automation directory 
a.	cd /etc/openhab2
b.	mkdir automation
4.	copied from sounds/automation to /etc/openhab2/automation
a.	cp -R /etc/openhab2/sounds/temp/automation/* /etc/openhab2/automation
5.	removed  groovy and javascript directories
a.	rm –r groovy 
b.	rm –r javascript
c.	in both the lib and jsr223 directories
I think there's an easier way to do this, but without detailed documentation similar to the OH installation, it's a struggle.

11. Download the standalone Jython 2.7.0 jar - the link is invalid and points to a 404 page. I used the following information 
Jython 2.7.0 is available through jython.org/download at https://search.maven.org/artifact/org.python/jython-standalone
Used path from https://community.openhab.org/t/jsr223-helper-libraries-jython-support-install-guide-openhab-2-5-wip/91026/2 to download “jar” file
And installed through similar process described above
copied to openhab/sounds directory through windows and then
cd /etc/openhab2/automation
mkdir jython
cd ./jython
cp /etc/openhab2/sounds/temp/jython-standalone-2.7.0.jar /etc/openhab2/automation/jython/jython-standalone-2.7.0.jar

Trust this helps. Thank you all the work and effort. 
My apologies for the somewhat unformatted text above. I have never worked with Git, so as a new OH user it's challenging to learn OH and Git at the same time.

**Comment by 5iver** [comment]
> I struggled with this a very long time

Next time, please ask for help here or in the forum and I will gladly help out.

The installation of both Jython and the helper libraries should be done through the [Jython addon](https://community.openhab.org/t/beta-testers-wanted-jython-addon-w-helper-libraries-requires-oh-2-5-x/86633), which is a lot easier than doing it manually :slightly_smiling_face:! I am about to push an update to the libraries, documentation, and to the add-ons. Manual installations are no longer necessary and those instructions will be archived.

> Thank you all the work and effort.

I'm the only maintainer ATM, so thank you!

**Comment by RubyBailey** [comment]
Thank you Scott,
That sounds great. 
At this time the helper libraries are installed and working on my system; which is great news given my current level of "limited" understanding. 
Let me know if there is any way that I can help. Just be aware that I'm somewhat new to OH as well as python, java script, etc. , so my help may be somewhat limiting or noobishly confusing 🙂. I'll try wherever I can and am always willing to learn.
Thanks again for your quick response.
