### ISSUE TITLE
[Feature Request] Add PIN code support for ideAlarm

### ISSUE THREAD

**Issue by fastlorenzo** [openhab-scripters/openhab-helper-libraries#74]
It would be good to have the ability to enter a PIN code to disarm the alarm.

I already implemented it locally, I'll try to make a PR once ideAlarm is fully migrated.

**Comment by openhab-5iver** [comment]
@fastlorenzo, ideAlarm and lucid have been migrated and the repo/org rename is done. It should be safe to get this in now.

**Comment by fastlorenzo** [comment]
Great, I’ll have a look at this when I have a bit of time

**Comment by fastlorenzo** [comment]
PR created #168

**Comment by openhab-5iver** [comment]
Closed due to lack of response in the submitted PR.
